### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GewoonMennoplays** [montlikadani/ScoreBoards#8]
Hello. If I change some permissions in plugin.yml, will the plugin then crash? I want to have my own, custom permissions.

With kind regards, 
Menno

**Comment by montlikadani** [comment]
It crashes because can not find it. Why would you like to have custom permissions?

**Comment by GewoonMennoplays** [comment]
I like to have custom perms, https://gyazo.com/975959a5c2f2b7eb9a77c4ef95d1bd3f

**Comment by montlikadani** [comment]
Maximum of the permission will be custom that indicates the scoreboard. (**scoreboards.scoreboard.seen**)

**Comment by montlikadani** [comment]
There will be no custom permissions.
